apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secrets
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
  GOOGLE_API_KEY: {{ .Values.secrets.googleApiKey | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | quote }}
