apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.config.database | quote }}
  POSTGRES_USER: {{ .Values.config.username | quote }}
  PGDATA: "/var/lib/postgresql/data/pgdata"
