apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - path: postgres-patch.yaml
